name: smart_checking
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  dio: ^5.7.2
  dartz: ^0.10.1
  camera: ^0.11.0
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.13.0
  shared_preferences : ^2.3.2
  intl: ^0.20.2


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/fonts/

  
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Light.otf
          weight: 300
        - asset: assets/fonts/Gotham-Book.otf
          weight: 400
        - asset: assets/fonts/Gotham-Medium.otf
          weight: 500
        - asset: assets/fonts/Gotham-Bold.otf
          weight: 700
    - family: Somatic
      fonts:
        - asset: assets/fonts/SomaticRounded.otf